return {
	wp_ap_escape = "Втеча!",
	wp_bank_escape = "Втеча!",
	wp_bridge_escape = "Втеча!",
	wp_slaughterhouse_escape = "Втеча!",
	wp_str_esc = "Втеча!",
	wp_uc_check_limo = "Перевірте лімузин",
	wp_uc_computer = "Продовжуйте хакерську атаку",
	wp_uc_escape = "Втеча!",
	wp_uc_interogate = "Дістаньте кодові слова",
	wp_uc_keyboard = "Скористайтеся клавіатурою",
	wp_uc_power = "Відновіть електропостачання",
	wp_uc_saw = "Розпиліть лімузин",
	wp_xsub_bbq = "Поговоріть з Мітчеллом",
	wp_xsub_door = "Відчинити Двері",
	wp_xsub_escape = "Втеча!",
	wp_xsub_hack = "Замініть систему",
	wp_xsub_outlet = "Увімкніть в розетку",
	wp_xsub_power = "Увімкніть живлення",
	wp_xsub_safe = "Дослідити Сейф",
	wp_xsub_sewer = "Каналізація",
	wp_xsub_shelter = "Дістанься до Укриття",
	wp_xsub_tnt = "Помістіть заряд",
	wp_xsub_waterhose = "Потягніть за шланг",
	wp_xsub_watertap = "Відкрий кран",
	wp_xsub_watervalve = "Відкрийте вентиль",
	}