name: Update Translations

on:
  push:
    branches:
      - main  # Вказати вашу основну гілку
    paths:
      - path/to/your/translations/*  # Вказати шлях до файлів перекладу

jobs:
  update-translations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Copy translation files
        run: |
          cp path/to/your/translations/* ./path/in/repo/ # Змінити на актуальний шлях

      - name: Commit and push changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add .
          git commit -m "Update translations from Crowdin"
          git push
