name: Update Translations

on:
  push:
    paths:
      - 'Crowdin/translated/**'  # Змінити на шлях до файлів CSV
      - 'converter.py'  # Змінити на шлях до вашого Python скрипта

jobs:
  update_translations:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas  # або інші бібліотеки, які можуть знадобитися

    - name: Run translation script
      run: python converter.py  # Змінити на шлях до вашого Python скрипта

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git add .
        git commit -m "Automated Lua file update" || echo "No changes to commit"
        git push "https://${GITHUB_TOKEN}@github.com/Parapando/Payday-2-UA.git" HEAD:crowdin_sync
