name: Update Translations

on:
  push:
    branches:
      - crowdin_sync  # Вказати основну гілку вашого репозиторію
    paths:
      - Crowdin/translated/**  # Вказати шлях до папки з CSV файлами

jobs:
  convert-csv-to-lua:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run conversion script
        run: |
          python converter.py  # Вказати правильний шлях до скрипта

      - name: Commit and push changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add .  # Додає всі зміни у проекті
          git commit -m "Automated Lua file update"
          git push
