name: Update Translations

on:
  push:
    branches:
      - crowdin_sync
    paths:
      - Crowdin/translated/**

jobs:
  convert-csv-to-lua:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run conversion script
        run: |
          python converter.py

      - name: Commit and push changes
        env:
          TOKEN: ${{ secrets.ACTIONS_PAT }}
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add .
          git commit -m "Automated Lua file update"
          git push "https://${TOKEN}@github.com/Parapando/Payday-2-UA" HEAD:main
